name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install dependencies
      run: npm install
      
    - name: Build for macOS
      if: runner.os == 'macOS'
      run: npm run dist:mac
      
    - name: Build for Linux
      if: runner.os == 'Linux'
      run: npm run dist:linux
      
    - name: Build for Windows
      if: runner.os == 'Windows'
      run: npm run dist:win
